### ISSUE TITLE
Documentation: Working with Genie apps

### ISSUE THREAD

**Issue by MathiasWedeken** [GenieFramework/Genie.jl#158]
As stated on several occasions the documentation, routes.jl is supposed live in the /config subfolder of a new app. However, after running 
```
Genie.newapp("MyGenieApp")
```
the routes.jl file resides in the root of the project/app. Furthermore, a routes.jl that lives inside /config does not have any effect.

**Comment by essenciary** [comment]
@MathiasWedeken Great point - the framework is on the last steps before v1 so it's undergoing massive cleanup and refactoring. Since the `routes` file can pretty much host a full Genie app, it made more sense to be placed more prominently. Documentation hasn't been updated yet. 

However, the `routes.jl` file is now supposed to be in the root of the app. Indeed, placing in inside `config/` won't make any difference. 

Sorry for the confusion - I'll update the guides.

**Comment by essenciary** [comment]
@MathiasWedeken I updated the README and pushed to #master

**Comment by xgdgsc** [comment]
I find it strange route.jl is created without write permissions.

**Comment by xgdgsc** [comment]
The page only says to create by `Genie.newapp("MyGenieApp")`. But what about next launch ? What should I run after it closed?

**Comment by essenciary** [comment]
@xgdgsc 

Yes, it is strange and needs to be addressed. It's because it's not created, instead it's copied from within the package and that's how the package is cloned. There is an open issue to address it. 

The recommended way to start the app is to use the utilities within the app's `bin/` folder. Alternatively, within the app's folder, if you have an open Julia REPL, you can do `Genie.loadapp()`.
