### ISSUE TITLE
Session key generation uses insecure random generator

### ISSUE THREAD

**Issue by chethega** [GenieFramework/Genie.jl#162]
Consider [this](https://github.com/GenieFramework/Genie.jl/blob/f92caaf98d50b320c87d19844443c558172d1b0e/src/Sessions.jl#L39) line. The used Mersenne Twister is not cryptographically secure. It would be definitely preferable to use a CSPRNG here. After thinking 5 minutes about this, the issue should be probably unexploitable; but still, better fix it (at the very least as a matter of hygiene).

Sorry for opening a drive-by-issue, this cropped up in a separate discussion on [here](https://github.com/JuliaLang/julia/issues/27614).

**Comment by chethega** [comment]
To clarify a possible fix: One could probably initialize `const CSPRNG = Random.RandomDevice()` and then use `rand(CSPRNG, UInt128)` for nonce generation.

To clarify attack scenarios: The application using genie.jl sometimes returns unhashed output of `rand()` calls to attackers. Then the attacker can recover the internal state of the mersenne twister. The secret token gets leaked through a separate bug / misconfiguration. Then the only remaining entropy are the generation time and the random stream position at generation. This is not enough entropy.

This attack scenario is entirely unnecessary and can be avoided by using a secure RNG. 

Using the system RNG is probably preferable to an explicit secure julia RNG. The reason for this is that it gives virtualization frameworks an opportunity to re-seed /dev/urandom on wakeup from snapshot (otherwise, the session key streams of two VMs that were woken up from the same snapshot would be related).

**Comment by essenciary** [comment]
@chethega Thanks for reporting this! I'll try to patch but it's out of my area of comfort / expertise. If you feel like making a PR to address this, I'd be more than happy to merge it ASAP.

**Comment by ViralBShah** [comment]
We should probably have an easy way to use cryptographically safe RNGs for such use cases. Can be provided as an external package.

**Comment by chethega** [comment]
Cf central [issue](https://github.com/JuliaLang/julia/issues/32954).

**Comment by UniqueTokens** [comment]
Thanks @chethega for the tip! @essenciary here is a fork commit to discuss the change: [Use CSPRNG in Sessions.id()](https://github.com/UniqueTokens/Genie.jl/commit/95de7e4d25e3ee7a440ee8411f5bd42dcf47486c)

- adds CSPRNG as recommended in https://github.com/GenieFramework/Genie.jl/issues/162#issuecomment-521406810
- removes `Dates.now()` and `hash(Genie)` from `Sessions.id()` because it lowers id entropy imho
- removes `try catch` block because I don't think it's necessary to catch any exceptions from new code
- adds `test/tests_Sessions_id.jl` to prove the id randomness if Genie `secret_token` is given
