### ISSUE TITLE
Access to fetch blocked by CORS policy - Issue #253

### ISSUE THREAD

**Issue by 3210jr** [GenieFramework/Genie.jl#255]
Hey,
Thanks for your awesome work. LOVE GENIE.jl!

The issue I am facing is exactly this recently closed issue: https://github.com/GenieFramework/Genie.jl/issues/253#issue-648181057 

**Additional context**
Please include the output of 
`julia> versioninfo()`
```
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_REVISE = auto
```

and
`pkg> st`
```
Status `~/test/testmodels/Project.toml`
  [31c24e10] Distributions v0.23.4
  [c43c736e] Genie v0.31.5
  [e6f89c97] LoggingExtras v0.4.1
  [cc2ba9b6] MLDataUtils v0.5.1
  [295af30f] Revise v2.7.3
  [4c63d2b9] StatsFuns v0.9.5
  [fce5fe82] Turing v0.13.0 #master (https://github.com/TuringLang/Turing.jl.git)
```

**Comment by essenciary** [comment]
@3210jr Thanks, I'll recheck

**Comment by essenciary** [comment]
@3210jr What errors are you getting? For me, it works perfectly. Is the request actually reaching the Genie app/server (do you see output in the console)? Because otherwise it's the browser itself that is blocking the request via the Content Security Policy. 

Here is a screenshot of accessing the code on localhost from genieframework.com: 
![image](https://user-images.githubusercontent.com/11292378/87970785-87dc8b80-cac4-11ea-9149-8ab69fd6c12c.png)

**Comment by essenciary** [comment]
I'm going to close this - I suggest looking into CSP https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP to configure the page on the client side.

**Comment by 3210jr** [comment]
Thanks @essenciary. I ended up just using a GET request but I just spinned up a new project and POST just worked out of the box! 
Thanks for looking into it and sorry that it was a dead end!

**Comment by essenciary** [comment]
No problem!

**Comment by wadehenning** [comment]
@3210jr  Would you be willing to share how you set up your `route` and how you are calling it?  I am having trouble reading my params.  #341
