### ISSUE TITLE
Add a verbose option to turn off logging, logo, etc

### ISSUE THREAD

**Issue by essenciary** [GenieFramework/Genie.jl#261]
Add a verbose option to turn off logging, logo, etc

**Comment by TommyXR** [comment]
I think there are many ways to handle the logging part. What I thought about is having a `logger` variable somewhere in the config, and replace instances of 
```julia
@info "msg"
@error "msg"
```

with

```julia
with_logger(Genie.config.logger) do
    @info "msg"
    @error "msg"
end
```

That way it's easy to disable logging by just passing a NullLogger in the config, or with some function that does it automatically.

Another option could be to just have a way to toggle logging off, and check the condition instead of using `with_logger`. I think the first one is better. I want to make sure this works with you too, but I'll make a quick drafty version as a proof of concept.

**Comment by essenciary** [comment]
I really like the idea of wrapping Genie.up in that, see if that works. Otherwise indeed, there aren't too many places where logging is performed within Genie.

**Comment by essenciary** [comment]
I remember solving this somehow but I can't remember how 🤷‍♂️
