### ISSUE TITLE
Cannot test unnamed project

### ISSUE THREAD

**Issue by rikhuijzer** [GenieFramework/Genie.jl#281]
**Describe the bug**
On Gitter, I promised to report an issue that I had with Genie last week. I tried to set up testing, which failed, as can be seen below.

**Error stacktrace**
```
(MyApp) pkg> test
ERROR: trying to test unnamed project
```

**To reproduce**
```julia
julia> using Genie

julia> Genie.newapp_webservice("MyApp")
...

julia> exit()

$> cd MyApp/

$> mkdir test

$> echo -e "using Test \nusing MyApp \n\n@testset \"MyApp\" begin \n@test 1 == 1 \nend" > test/runtests.jl

$> julia

pkg> activate .

(MyApp) pkg> test
ERROR: trying to test unnamed project
```

**Expected behavior**
```
(MyApp) pkg> test
Test Summary: | Pass  Total
MyApp         |    1      1
```

**Additional context**
```julia
julia> versioninfo() 
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  ...

pkg> st
...
[c43c736e] Genie v1.1.0
...
[8dfed614] Test
```

**Comment by mirkobunse** [comment]
Hi,

I urgently needed some unit tests. Fixing your issue along the way immediately led to some other issues, which can, fortunately, be solved as well.

## Solution (partial)

you can solve the `trying to test unnamed project` error by adding a name and a uuid to your `Project.toml`:

```
name = "arbitrary name"
uuid = "generated uuid"
authors = ["Your Name <and@email.address>"]
version = "0.1.0"

[deps]
...
```

The uuid can simply be generated from the Julia REPL:

```julia
using UUIDs
uuid4()
```

Next, you can create a file `test/runtests.jl` which will be executed on calling `] test`.


## Follow-up issue: Testing controller modules

I needed to test my controller modules, e.g. `app/resources/admin/AdminController.jl`. However, the controller modules are not in the scope of the main module at `src/AppName.jl`. They are in scope when `bin/repl` is running, but that does not help when calling `] test`.

It turns out that controller modules are brought into scope by additions to the `LOAD_PATH`. You can see what happens in Genie's source code: https://github.com/GenieFramework/Genie.jl/blob/3d7f0abd52773832dfae46b49d6f364436864eaa/src/genie_module.jl#L89 Basically, everything is added to the `LOAD_PATH` and later included, I guess.

We can obtain the same scope as the `bin/repl` in our unit tests by **beginning our unit tests as follows:**

```julia
# tests/runtests.jl
import Pkg
include("../bootstrap.jl") # this is precisely what bin/repl does

using AdminController, Test # now, we can test controllers

# ...
```

And we need one more thing: A working `test/Project.toml`.

```
$> bin/repl    # it is important to start from here
(AppName) pkg> activate test    # activate test/Project.toml independent of whether it exists
(test) pkg> instantiate    # add all dependencies that bin/repl uses
(test) pkg> activate .    # go back to the main Project.toml
(SecretSanta) pkg> test    # the tests can now be started
```

From now on, calling `] test` should work with the same scope that `bin/repl` has (even if we start Julia without `bin/repl`).


## Discussion on unit testing with Genie.jl

AFAIK from other discussions, altering the `LOAD_PATH` is no good style. It's cleaner to have all code in the `src` directory, which always is in the `LOAD_PATH`, anyways. But that topic is probably worth a seperate discussion.

**Comment by essenciary** [comment]
Thanks - yes, this needs a bit of thinking. I would start by distinguishing _packages_ from _applications_. A Genie _app_ is an application, not a package. Distinction here: https://discourse.julialang.org/t/distinguishing-projects-from-packages/153/41?u=essenciary

As such: 
a) we can have additional data added to the `Project.toml` file. However, what we get now it's what `Pkg` generates. The `Project.toml` file is not touched by Genie. We could switch to `PkgTemplates.jl` but that means an extra dependency for a very rarely used feature (creating new apps). 
b) because a Genie app is not a package, there is not need to put the code in `src/`. On the contrary, all MVC frameworks employ custom file structures, which make it easy for humans to navigate and discern the various MVC components. 
c) can you please detail the problem with `LOAD_PATH`, I'm not aware of any issues?

**Comment by mirkobunse** [comment]
I totally agree to a) and d). Thanks for pointing out the difference between packages and applications.

I guess b) is mostly a matter of personal preferences - a custom file structure that discerns MVC could just as well be defined in `src/`, say `src/model`, `src/view` etc. My personal preference would be to have all code there, to follow the Julia package convention. However, I see that changing this now would break existing Genie apps.

Using `LOAD_PATH` is not a problem. However, it has the disadvantage that code loaded through extra `LOAD_PATH` entries can produce different results, depending on whether the `LOAD_PATH` is altered elsewhere. Say, you have a module `somePlace/Foo.jl` and a module `anotherPlace/Foo.jl`, then the order of directories matters, and a user could "inject" a module some place it does not belong; that user will struggle when he is not aware of what just happened. However, without sacrificing the existing directory structure, using `LOAD_PATH` will remain a necessity.

Let me say that I do enjoy Genie already as it is, despite these points of discussion. Thanks for all the effort!

Want me to spin up a PR on the test generator?

**Comment by essenciary** [comment]
@mirkobunse Moving the whole structure into the `src/` folder might actually be a good compromise to be both compatible with the Julia best practices while still having a neat MVC file structure. I'll run some tests and we could roll it in v2.0. 

Thanks for the nice words, I'm glad you enjoy building with it. If you can contribute the test generator based on the approach you described above would be awesome, thanks!

**Comment by essenciary** [comment]
The unit testable app features have now been merged into master and are about to be tagged. Thank you for the contribution! Closing this.
