### ISSUE TITLE
Rewrite the repl.bat script to be run from anywhere

### ISSUE THREAD

**Issue by DhruvaSambrani** [GenieFramework/Genie.jl#313]
**Is your feature request related to a problem? Please describe.**
The repl.bat script can only be run from the bin folder as the cwd. This makes it weird to use in other scripts and such

**Describe the solution you'd like**
By using %1-9 variables in batch scripting, the bat script should get the relative files.

**Describe alternatives you've considered**
Atleast make it similar to the linux version

**Comment by essenciary** [comment]
@DhruvaSambrani Thanks. 
* can you please detail how that "makes it weird to use in other scripts and such"?
* "By using %1-9 variables in batch scripting, the bat script should get the relative files" I'm not much of a windows script expert so please make a PR. 
* "Atleast make it similar to the linux version" - that was actually recently introduced (I think for apps generated starting with Genie 1.9.2) due to deeper changes in Genie apps and because I was never a fan of win scripts working differently from *nix.

**Comment by DhruvaSambrani** [comment]
> can you please detail how that "makes it weird to use in other scripts and such"?
Basically if I need to start the server from another script/exec/whatever, then I need to first cd into bin and then run the bat file, then cd back, OR i need to pass a working directory argument. But the repl.bat should JustWork(TM) from any cwd

>"By using %1-9 variables in batch scripting, the bat script should get the relative files" I'm not much of a windows script expert so please make a PR.
My bad, its %0 and some extensions. What files do I need to change?

**Comment by DhruvaSambrani** [comment]
See https://ss64.com/nt/syntax-args.html for info on args and extensions

**Comment by DhruvaSambrani** [comment]
> What files do I need to change?

I think I need to change all the `write` functions in  https://github.com/GenieFramework/Genie.jl/blob/52c796cd66282db762fb425f7709929a2d17cf79/src/Generator.jl#L127
from `... -- ../$(Genie.BOOTSTRAP_FILE_NAME) ...` to `... -- %~dp0/../$(Genie.BOOTSTRAP_FILE_NAME) ...`

The `~dp` will expand the drive and parent directory as mentioned in the link in the previous message

**Comment by DhruvaSambrani** [comment]
If I call the repl.bat file as `programming\Julia\MyGenieApp\bin\repl.bat` from **anywhere**, even another drive, it will expand to `C:\Users\user\programming\Julia\MyGenieApp\bin\..\bootstrap.jl`

**Comment by essenciary** [comment]
@DhruvaSambrani Thank you!
