### ISSUE TITLE
Genie should not touch request headers

### ISSUE THREAD

**Issue by UniqueTokens** [GenieFramework/Genie.jl#432]
HTTP header names are case-insensitive, according to [RFC 2616](https://www.ietf.org/rfc/rfc2616.txt).

However, Genie changes the case of ALL request headers via `Headers.normalize_headers` for its own purposes.  For example, _X-Real-IP_ becomes _X-Real-Ip_. In particular, if a proxy is involved, this leads to errors that are difficult to understand. Genie unnecessarily forces the application developers to do some annoying extra work to fix this.

**Comment by essenciary** [comment]
We need to do that in order to simplify/speed-up the look-up for various headers used internally. But indeed, this can be a problem. 

We can fix it easily with 2 solutions: 
1) we can define a list of standard headers we use internally, and only normalize these ("Origin", "Access-Control-Allow-Origin", etc). Pro: keeps the headers collection small. Con: some users might still expect these headers in different casing.  
2) create normalized headers but do not remove the original ones. Pro: original headers stay untouched. Cons: potentially duplicates the size of the headers collection and can be confusing for users (eg if they want to update a header, which one should they update or they'll need to update multiple). 

The harder solution would be 3) to implement some form of case-insensitive lookup (for read/write access to the headers collection).

So I'd say we can start with 1 and see how it goes?

**Comment by iskyd** [comment]
@essenciary any news on this? I think we can do something similar to symfony, so use loswercase for keys.
strtr($key, self::UPPER, self::LOWER); where upper is '_ABCDEFGHIJKLMNOPQRSTUVWXYZ' and lower '-abcdefghijklmnopqrstuvwxyz'.
Example: strtr("Access_Control-Allow-Origin", $upper, $lower) ->  access-control-allow-origin (note also the _ in the key).

This is done in get/has header methods.

Let me know what do you think.

**Comment by essenciary** [comment]
Sorry, haven't had a chance to work on this yet but I gave it some thought: 
* the best approach would be to leave the headers untouched and perform a case insensitive match. This means that we can't get the benefits of an indexed data structure anymore, having to iterate over all the elements anyway. As such, storing the headers in an array would make more sense - and this explains why HTTP.jl uses a Vector of Pair for the headers. 
* to make the refactoring simpler we can implement a case insensitive Dict which performs this iterative lookup over the keys internally. 
* however, this is a breaking change as some users might rely on the transformation of the headers so it would have to go in v5. There's quite a few valuable breaking features so we should start thinking about it soon.

**Comment by UniqueTokens** [comment]
Fixed in v5.
