### ISSUE TITLE
Export Requests.getheaders [feature request]

### ISSUE THREAD

**Issue by curioustolearn** [GenieFramework/Genie.jl#629]
**Is your feature request related to a problem? Please describe.**
I need to get the host information in one of my routes. I can get it as Genie.Requests.getheaders(). However, since getheaders() is not exported in the Requests module, I am wondering if this is okay to do, or is it an internal thing that I should not rely on. If I want to get the header information, should I rely on HTTP.jl, or should it be exported in Genie.Requests.

Thank you.

**Describe the solution you'd like**
Either knowing that it is okay to use `Genie.Requests.getheaders()`. Or, if only exported functions should be relied on, then requesting that it be exported.

**Comment by essenciary** [comment]
It's definitely safe to use. I can't remember why it's not exported by I suspect that it's because there's also a `Responses.getheaders()` that is already exported. As usually both `Requests` and `Responses` are used in the same scope, exporting from both would result in none being exported (because of the name conflict).

**Comment by curioustolearn** [comment]
Thank you for clarifying this. And, thanks very much for creating this framework. I am going to try and look at how I can contribute to it.
