### ISSUE TITLE
Typos in "your first dashboard" page in the website

### ISSUE THREAD

**Issue by chunjiw** [GenieFramework/Genie.jl#684]
I couldn't find the repo for https://genieframework.com/ website, I assume it is not open source anymore. I don't know where to report this so I'm doing it here.

In https://learn.genieframework.com/guides/first-dashboard, I get error 

`ERROR: Couldn't find a Genie app file in /path/to/app/ (bootstrap.jl, routes.jl or app.jl).`

So obviously I changed App.jl to app.jl and it works.

Also, the input variable is upper case `N` but in `ui()` it is lower case `n`.

Also, the page didn't mention I need to `Genie.loadapp()` again to see the slider. (Or is this a bug?)

**Comment by essenciary** [comment]
Thanks @chunjiw !
@PGimenez can you please check?

**Comment by PGimenez** [comment]
Thanks for reporting this @chunjiw! I've fixed the typos and updated the site. 

The repo for the docs site is at https://github.com/GenieFramework/GenieFrameworkDocs/
Also, you can find an "Edit this page" link at the bottom of each page in case you'd like to contribute a fix.

Regarding having to use `Genie.loadapp()`. That should not be necessary after the UI file is loaded. Any changes to it should be refreshed in the browser. Make sure to launch the app with an already existing `ui.jl` file, otherwise you'll need to reload the app.
